version: '3'

services:
  mysql:
    container_name: hoon-wiki
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "wiki"
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Seoul'
    ports:
      - '3306:3306'
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'