spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100

---
spring.config.activate.on-profile: local
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: ''
    url: jdbc:mysql://localhost:3306/wiki?useSSL=false&serverTimezone=Asia/Seoul

---
spring.config.activate.on-profile: test
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: h2
  datasource:
    driver-class-name: org.h2.Driver
    username: 'root'
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL